jibe_pic_scraper/config/routes.rb
Rails.application.routes.draw do

  resources :insta_accounts do
    collection do
      get "insta_callback"
      get "insta_connect"
    end
  end

  resources :flickr_accounts do
    collection do
      get "flickr_callback"
      get "flickr_connect"
    end
  end

   root 'insta_accounts#index'

end

jibe_pic_scraper/app/models/flickr_account.rb
class FlickrAccount < ActiveRecord::Base
end

jibe_pic_scraper/app/models/insta_account.rb
class InstaAccount < ActiveRecord::Base
end

jibe_pic_scraper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jibe_pic_scraper/app/controllers/flickr_accounts_controller.rb
class FlickrAccountsController < ApplicationController

  require 'flickr'

  CALLBACK_URL = "http://jibe_pic_scraper.dev/flickr_accounts/flickr_callback"

  # GET /flickr_accounts
  # GET /flickr_accounts.json
  def index
    @flickr_accounts = FlickrAccount.all
  end

  # GET /flickr_accounts/1
  # GET /flickr_accounts/1.json
  def show
  end

  # GET /flickr_accounts/new
  def new
    @flickr_account = FlickrAccount.new
  end

  # GET /flickr_accounts/1/edit
  def edit
  end

  # POST /flickr_accounts
  # POST /flickr_accounts.json
  def create
    @flickr_account = FlickrAccount.new(flickr_account_params)

    if @flickr_account.save
      redirect_to flickr_accounts_path
    else
      render :new
    end

    # respond_to do |format|
    #   if @flickr_account.save
    #     format.html { redirect_to @flickr_account, notice: 'Flickr account was successfully created.' }
    #     format.json { render :show, status: :created, location: @flickr_account }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @flickr_account.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /flickr_accounts/1
  # PATCH/PUT /flickr_accounts/1.json
  def update
    # respond_to do |format|
    #   if @flickr_account.update(flickr_account_params)
    #     format.html { redirect_to @flickr_account, notice: 'Flickr account was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @flickr_account }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @flickr_account.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /flickr_accounts/1
  # DELETE /flickr_accounts/1.json
  def destroy
    # @flickr_account.destroy
    # respond_to do |format|
    #   format.html { redirect_to flickr_accounts_url, notice: 'Flickr account was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end


  def flickr_connect
    flickr =  Flickr.new("cff675a60acc72ab77c7b3f52655b690")

    @recentphotos = flickr.photos

    raise flickr.inspect
  #     Flickraw.api_key = "cff675a60acc72ab77c7b3f52655b690"
  #     Flickraw.shared_secret = "ba164b12cdb9ac3c"
  #
  #     token = flickr.get_request_token
  #     auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'delete')
  #
  #     raise auth_url
  #
  #     redirect_to Flickraw.authorize_url(:redirect_uri => CALLBACK_URL)
   end



  def flickr_callback
      token = flickr.get_request_token
      auth_url = flickr.get_authorize_url(token['oauth_token'], :perms => 'delete')

      raise auth_url

      begin
        flickr.get_access_token(token['oauth_token'], token['oauth_token_secret'], verify)
        login = flickr.test.login
        puts "You are now authenticated as #{login.username} with token #{flickr.access_token} and secret #{flickr.access_secret}"
      rescue FlickRaw::FailedResponse => e
        puts "Authentication failed : #{e.msg}"
      end
      # @dctech = client.tag_recent_media('dctech')

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flickr_account
      @flickr_account = FlickrAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flickr_account_params
      params.require(:flickr_account).permit(:username)
    end
end

jibe_pic_scraper/app/controllers/insta_accounts_controller.rb
class InstaAccountsController < ApplicationController

  CALLBACK_URL = "http://jibe_pic_scraper.dev/insta_accounts/insta_callback"
  
  def index
    @insta_accounts = InstaAccount.all
  end

  def new
    @insta_account = InstaAccount.new
  end

  def show
  end

  def edit
  end

  def create
    @insta_account = InstaAccount.new(insta_account_params)

    if @insta_account.save
      redirect_to insta_accounts_path
    else
      render :new
    end

  end

  def update
  end

  def destroy
  end

  def insta_connect
    Instagram.configure do |config|
      config.client_id = "b605ca12cf5b4686a7c989be77759b8b"
      config.client_secret = "f4210aac39b34dde8cb0c46f4aee542e"

    end

    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)

  end

  def insta_callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token

    client = Instagram.client(:access_token => session[:access_token])

    @dctech = client.tag_recent_media('dctech')

  end

  private

    def insta_account_params
      params.require(:insta_account).permit(:username)
    end
end

jibe_pic_scraper/app/helpers/application_helper.rb
module ApplicationHelper
end

jibe_pic_scraper/app/helpers/flickr_accounts_helper.rb
module FlickrAccountsHelper
end

jibe_pic_scraper/app/helpers/insta_accounts_helper.rb
module InstaAccountsHelper
end

jibe_pic_scraper/app/views/flickr_accounts/_form.html.erb
<%= form_for(@flickr_account) do |f| %>
  <% if @flickr_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flickr_account.errors.count, "error") %> prohibited this flickr_account from being saved:</h2>

      <ul>
      <% @flickr_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jibe_pic_scraper/app/views/flickr_accounts/edit.html.erb
<h1>Editing Flickr Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @flickr_account %> |
<%= link_to 'Back', flickr_accounts_path %>

jibe_pic_scraper/app/views/flickr_accounts/flickr_callback.html.erb
<%= "please work"%>

jibe_pic_scraper/app/views/flickr_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flickr Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Access token</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flickr_accounts.each do |flickr_account| %>
      <tr>
        <td><%= flickr_account.access_token %></td>
        <td><%= flickr_account.username %></td>
        <td><%= link_to 'Show', flickr_account %></td>
        <td><%= link_to 'Edit', edit_flickr_account_path(flickr_account) %></td>
        <td><%= link_to 'Destroy', flickr_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flickr account', new_flickr_account_path %>

jibe_pic_scraper/app/views/flickr_accounts/new.html.erb
<h1>New Flickr Account</h1>

<%= render 'form' %>

<%= link_to 'Back', flickr_accounts_path %>

jibe_pic_scraper/app/views/flickr_accounts/show.html.erb
<h1>FlickrAccounts#show</h1>
<p>Find me in app/views/flickr_accounts/show.html.erb</p>

jibe_pic_scraper/app/views/insta_accounts/_form.html.erb
<%= form_for @insta_account do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %>
  <%= f.submit %>
<% end %>

jibe_pic_scraper/app/views/insta_accounts/create.html.erb
<h1>InstaAccounts#create</h1>
<p>Find me in app/views/insta_accounts/create.html.erb</p>

jibe_pic_scraper/app/views/insta_accounts/destroy.html.erb
<h1>InstaAccounts#destroy</h1>
<p>Find me in app/views/insta_accounts/destroy.html.erb</p>

jibe_pic_scraper/app/views/insta_accounts/edit.html.erb
<h1>InstaAccounts#edit</h1>
<p>Find me in app/views/insta_accounts/edit.html.erb</p>

jibe_pic_scraper/app/views/insta_accounts/index.html.erb
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insta_accounts.each do |account| %>
    <%= link_to 'See #dctech pictures for Instagram', insta_connect_insta_accounts_path(account) %>
      <tr>
        <td><%= account.username %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_insta_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

jibe_pic_scraper/app/views/insta_accounts/insta_callback.html.erb
<% sorted_dc = @dctech.sort_by { |a| -a.comments["count"]} %>
<%= sorted_dc.each do |item| %>
  <%= image_tag(item.images["thumbnail"]["url"])%>
<br>
<%= item.comments["count"] %>
<br>
<%- end %>

jibe_pic_scraper/app/views/insta_accounts/new.html.erb
<%= render 'form' %>

jibe_pic_scraper/app/views/insta_accounts/show.html.erb
<h1>InstaAccounts#show</h1>
<p>Find me in app/views/insta_accounts/show.html.erb</p>

jibe_pic_scraper/app/views/insta_accounts/update.html.erb
<h1>InstaAccounts#update</h1>
<p>Find me in app/views/insta_accounts/update.html.erb</p>

jibe_pic_scraper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JibePicScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>